name = "impzimzoom"
main = "src/index.ts"
compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "impzimzoom"
database_id = "7cbb0e63-48f1-4e7a-ac75-4d9ce197af10"

