name = "todo-tele-bot"
main = "src/index.ts"
compatibility_date = "2024-03-01"

# Use the newer nodejs_compat flag for better Node.js compatibility
compatibility_flags = ["nodejs_compat"]

# Configure your database
[[d1_databases]]
binding = "DB"
database_name = "todo_tele_bot"
database_id = "42339472-ce91-4a72-9d49-81a244fa05e0"





