name = "ai-asap-bot"
main = "src/index.ts"
compatibility_date = "2024-03-01"

# Use the newer nodejs_compat flag for better Node.js compatibility
compatibility_flags = ["nodejs_compat"]

# Configure your database
[[d1_databases]]
binding = "DB"
database_name = "ai-asap-bot"
database_id = "aa72824e-595e-4457-98c3-2f5f00593416"




